name: (Manual Trigger)Build and Push to Docker Hub

# 觸發方式？
on:
  workflow_dispatch:        #「手動執行」的按鈕
    
# on:
#   push:                   
#     branches: [ "main" ]  # 當有程式碼 push 到 main 分支時

env:
  # 這裡會自動抓 Secret 帳號 + 專案名稱
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/demo-golang

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    # 1. 下載程式碼到虛擬機
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. 設定 Docker Buildx 
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 3. 登入 Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 這一步是用來產生 "a1b2c3d" 這種短版版號的
    - name: Get Short SHA
      id: vars   # 這個 id 很重要，下面的 steps.vars 就是在叫它
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    # 4. 打包 Image 並推送到 Docker Hub
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: . # 找 Dockerfile 檔案
        push: true
        # 下面這行格式是: 你的帳號/你的專案名:標籤
        # 注意：變數名稱要跟 secret 一樣
        # latest 用來看， sha用來給CD辨別差異用的
        tags: |
          ${{ env.IMAGE_NAME }}:latest 
          ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}