name: Build and Push to Docker Hub

# 觸發方式？
on:
  workflow_dispatch:        #「手動執行」的按鈕
    
# on:
#   push:                   
#     branches: [ "main" ]  # 當有程式碼 push 到 main 分支時

env:
  # 這裡會自動抓 Secret 帳號 + 專案名稱
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/demo-golang

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    # 1. 下載程式碼到虛擬機
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. 設定 Docker Buildx 
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 3. 登入 Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 4. 打包 Image 並推送到 Docker Hub
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        # 下面這行格式是: 你的帳號/你的專案名:標籤
        # 注意：變數名稱要跟 secret 一樣
        tags: |
          ${{ env.IMAGE_NAME }}:latest
          ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}